[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200

unchecked_cheatcode_artifacts = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# Allow scripts/tests to read and write specific files
fs_permissions = [
  { access = "read", path = "/Users/dippy/Documents/code/minefun" },
  { access = "write", path = "/Users/dippy/Documents/code/minefun/.env.depin" }
]
